# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pirunner-testing:
    runs-on: self-hosted
    steps:
      - name: pi uname
        id: pi_uname
        run: uname -a

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: sudo sh src/build.sh

      # Create a new release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          
      - name: Create Asset
        id: create_asset
        run: |
          sudo ln *.img my-pi-image-${{ steps.create_release.outputs.id }}.img
          zip -j my-pi-image-${{ steps.create_release.outputs.id }} my-pi-image-${{ steps.create_release.outputs.id }}.img

      # Upload our completed image to the new release
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./my-pi-image-${{ steps.create_release.outputs.id }}.zip
          asset_name: my-pi-image-${{ steps.create_release.outputs.id }}.zip
          asset_content_type: application/zip
